surgery:
  label: Surgery
  description: All posts related to surgery.

surgical-education:
  label: Surgical Education
  description: Insights and content on surgical education.

healthcare-quality:
  label: Healthcare Quality
  description: Discussions and research on healthcare quality improvement.

AI:
  label: AI
  description: Topics related to artificial intelligence in healthcare and beyond.

automation:
  label: Automation
  description: The role and impact of automation in healthcare and surgery.

burnout:
  label: Burnout
  description: Addressing burnout in medical and healthcare professions.

healthcare:
  label: Healthcare
  description: General topics and insights related to the healthcare system.
